openapi: 3.0.0
info:
  title: Kapu$ta API
  version: 1.0.3
  description: API for personal finance management.
servers:
  - url: https://kapusta-eta.vercel.app
  - url: http://localhost:3001

paths:
  /auth/register:
    post:
      tags:
        - Authorization
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "201":
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
        "409":
          description: Email already in use
        "400":
          description: Invalid input data

  /auth/login:
    post:
      tags:
        - Authorization
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: User successfully logged in
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "403":
          description: Invalid email or password
        "400":
          description: Invalid input data

  /auth/logout:
    post:
      tags:
        - Authorization
      summary: User logout
      security:
        - BearerAuth: []
      responses:
        "204":
          description: User successfully logged out
        "401":
          description: Unauthorized
        "400":
          description: No token provided
        "404":
          description: User not found

  /auth/refresh:
    post:
      tags:
        - Authorization
      summary: Refresh access token
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenRequest"
      responses:
        "200":
          description: Access token successfully refreshed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RefreshTokenResponse"
        "401":
          description: Unauthorized or Invalid refresh token
        "400":
          description: Invalid input data
        "404":
          description: User not found

  /user/balance:
    patch:
      tags:
        - User
      summary: Update user balance
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBalanceRequest"
      responses:
        "200":
          description: Balance successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateBalanceResponse"
        "400":
          description: Invalid input data
        "401":
          description: Unauthorized
        "404":
          description: User not found

  /user:
    get:
      tags:
        - User
      summary: Get current user data
      security:
        - BearerAuth: []
      responses:
        "200":
          description: User data successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    format: email
                  balance:
                    type: number
                  transactions:
                    type: array
                    items:
                      $ref: "#/components/schemas/Transaction"
        "401":
          description: Unauthorized

  /transaction/expense:
    get:
      tags:
        - Transactions
      summary: Get user expenses
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successfully retrieved user expenses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "400":
          description: no token provided
        "401":
          description: Unauthorized
        "404":
          description: User not found

    post:
      tags:
        - Transactions
      summary: Add new expense
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddTransactionRequest"
      responses:
        "200":
          description: Expense successfully added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddTransactionResponse"
        "400":
          description: Invalid input data
        "401":
          description: Unauthorized
        "404":
          description: User not found

  /transaction/income:
    get:
      tags:
        - Transactions
      summary: Get user incomes
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successfully retrieved user incomes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "400":
          description: no token provided
        "401":
          description: Unauthorized
        "404":
          description: User not found

    post:
      tags:
        - Transactions
      summary: Add new income
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddTransactionRequest"
      responses:
        "200":
          description: Income successfully added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddTransactionResponse"
        "400":
          description: Invalid input data
        "401":
          description: Unauthorized
        "404":
          description: User not found

  /transaction/period-data:
    get:
      tags:
        - Transactions
      summary: Get transactions data for a specific period
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: date
          required: true
          schema:
            type: string
            pattern: '^(\d{4}|\d{4}-\d{2})$'
          description: Date in format YYYY or YYYY-MM
      responses:
        "200":
          description: Successfully retrieved transactions data for the period
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PeriodDataResponse"
        "400":
          description: Invalid date format
        "401":
          description: Unauthorized
        "404":
          description: User not found

  /transaction/expense-categories:
    get:
      tags:
        - Transactions
      summary: Get expense categories
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successfully retrieved expense categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "401":
          description: Unauthorized
        "404":
          description: User not found

  /transaction/income-categories:
    get:
      tags:
        - Transactions
      summary: Get income categories
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successfully retrieved income categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "401":
          description: Unauthorized
        "404":
          description: User not found

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          example: example@example.com
        password:
          type: string
          minLength: 6
          example: Password123
      required:
        - email
        - password
    RegisterResponse:
      type: object
      properties:
        user:
          type: object
          properties:
            email:
              type: string
              example: test@example.com
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          example: example@example.com
        password:
          type: string
          example: Password123
      required:
        - email
        - password

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        refreshToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        sid:
          type: string
          example: TvhtZeGfqdsGJM8Kx6ncI
        user:
          type: object
          properties:
            email:
              type: string
              example: test@example.com
            balance:
              type: number
              example: 4522
            id:
              type: string
              example: vAuSEoLO53AwiZHWCiAmM
            transactions:
              type: array
              items:
                type: object
                properties:
                  _id:
                    type: string
                    example: 66f750c939f7039284fa05ac
                  description:
                    type: string
                    example: Groceries
                  amount:
                    type: number
                    example: 122
                  date:
                    type: string
                    example: 2023-06-05
                  category:
                    type: array
                    items:
                      type: string
                    example: Food
    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string
      required:
        - refreshToken

    RefreshTokenResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        sid:
          type: string

    UpdateBalanceRequest:
      type: object
      properties:
        balance:
          type: number
          example: 1000
      required:
        - balance

    UpdateBalanceResponse:
      type: object
      properties:
        email:
          type: string
          format: email
          example: example@example.com
        balance:
          type: number
          example: 1000
    Transaction:
      summary: Income or Expense
      type: object
      properties:
        _id:
          type: string
        description:
          type: string
          example: "Grocery shopping"
        amount:
          type: number
          example: 1000
        date:
          type: string
          format: date
          example: 2024-05-01
        category:
          type: array
          items:
            type: string
            enum:
              [
                "Products",
                "Alcohol",
                "Entertainment",
                "Health",
                "Transport",
                "Housing",
                "Technique",
                "Communal, communication",
                "Sports, hobbies",
                "Education",
                "Other",
              ]
        type:
          type: string
          enum: ["income", "expense"]
          example: income
    AddTransactionRequest:
      type: object
      properties:
        description:
          type: string
          example: "Grocery shopping"
        amount:
          type: number
          example: 1000
        date:
          type: string
          format: date
          example: 2024-05-01
        category:
          oneOf:
            - type: string
            - type: array
              items:
                type: string
          enum:
            - Products
            - Alcohol
            - Entertainment
            - Health
            - Transport
            - Housing
            - Technique
            - "Communal, communication"
            - "Sports, hobbies"
            - Education
            - Other
            - Salary
            - "Add. income"
      required:
        - description
        - amount
        - date
        - category

    AddTransactionResponse:
      type: object
      properties:
        newBalance:
          type: number
          example: 1000
        transaction:
          $ref: "#/components/schemas/Transaction"

    PeriodDataResponse:
      type: object
      properties:
        incomes:
          type: object
          properties:
            total:
              type: number
              example: 1000
            incomesData:
              type: object
              example: 2024-05-01
        expenses:
          type: object
          properties:
            total:
              type: number
              example: 1000
            expensesData:
              type: object
              example: 2024-05-01

    ExpenseCategories:
      type: object
      properties:
        categories:
          type: array
            type: string
            enum:
            [
              "Products",
              "Alcohol",
              "Entertainment",
              "Health",
              "Transport",
              "Housing",
              "Technique",
              "Communal, communication",
              "Sports, hobbies",
              "Education",
              "Other",
            ]
      description: Expense categories
    IncomeCategories:
      type: object
      properties:
        categories:
          type: array
            type: string
            enum: ["Salary", "Add. income"]
      description: Income categories
securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT